export enum ErrorCode {
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  POST_NOT_FOUND = 'POST_NOT_FOUND',
  IMAGE_NOT_FOUND = 'IMAGE_NOT_FOUND',
  MISSING_IMAGE = 'MISSING_IMAGE',
  INVALID_ID = 'INVALID_ID',
  IMAGE_ALREADY_EXIST = 'IMAGE_ALREADY_EXIST',
  FILE_NOT_SUPPORTED = 'FILE_NOT_SUPPORTED',
  UNABLE_TO_DELETE_THIS_IMAGE = 'UNABLE_TO_DELETE_THIS_IMAGE',
}
