export enum SuccessCode {
  COMMENT_SUCCESSFULLY_DELETED = 'COMMENT_SUCCESSFULLY_DELETED',
  REPLY_SUCCESSFULLY_CREATED = 'REPLY_SUCCESSFULLY_CREATED',
  COMMENT_SUCCESSFULLY_CREATED = 'COMMENT_SUCCESSFULLY_CREATED',
  COMMENT_SUCCESSFULLY_EDITED = 'COMMENT_SUCCESSFULLY_EDITED',
  PASSWORD_SUCCESSFULLY_REDEFINED = 'PASSWORD_SUCCESSFULLY_REDEFINED',
  REPLY_SUCCESFULLY_DELETED = 'REPLY_SUCCESFULLY_DELETED',
  VERIFICATION_CODE_SUCCESSFULLY_SENT = 'VERIFICATION_CODE_SUCCESSFULLY_SENT',
  EMAIL_SUCCESSFULLY_VERIFIED = 'EMAIL_SUCCESSFULLY_VERIFIED',
  RECOVERY_PASSWORD_LINK_SENT = 'RECOVERY_PASSWORD_LINK_SENT',
  PROFILE_SUCCESSFULLY_EDITED = 'PROFILE_SUCCESSFULLY_EDITED',
}
