export enum SuccessCode {
  COMMENT_SUCCESSFULLY_DELETED = 'COMMENT_SUCCESSFULLY_DELETED', // Not translated
  REPLY_SUCCESSFULLY_CREATED = 'REPLY_SUCCESSFULLY_CREATED', // Not translated
  COMMENT_SUCCESSFULLY_CREATED = 'COMMENT_SUCCESSFULLY_CREATED', // Not translated
  COMMENT_SUCCESSFULLY_EDITED = 'COMMENT_SUCCESSFULLY_EDITED', // Not translated,
  PASSWORD_SUCCESSFULLY_REDEFINED = 'PASSWORD_SUCCESSFULLY_REDEFINED', // Not translated
  REPLY_SUCCESFULLY_DELETED = 'REPLY_SUCCESFULLY_DELETED', // Not translated
  VERIFICATION_CODE_SUCCESSFULLY_SENT = 'VERIFICATION_CODE_SUCCESSFULLY_SENT', // Not translated
  EMAIL_SUCCESSFULLY_VERIFIED = 'EMAIL_SUCCESSFULLY_VERIFIED', // Not translated
  RECOVERY_PASSWORD_LINK_SENT = 'RECOVERY_PASSWORD_LINK_SENT', // Not translated
  PROFILE_SUCCESFULLY_EDITED = 'PROFILE_SUCCESFULLY_EDITED', // Not translated
}
